### ISSUE TITLE
TypeError: Object of type 'method' is not JSON serializable

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy-REST#1]
I'm not using REST, but I've been trying things for a while.

I had already reported this [1] problem in version 0.4.1 that was solved in 0.4.2.

Using bloggy.py

# api.py 
from bloggy import app, Post
posts = app.rest_module(__name__, 'api_post', Post, url_prefix='posts')

http://127.0.0.1:8000/posts
Now this error is occurring [2]. What I see is that neither weppy (1.0.6) nor weppy-REST (0.4.2) have changed this time. I do not remember updating python either. Tested with python 27, 34 and 36, in every case fails.

[1] https://groups.google.com/forum/#!topic/weppy-talk/z4AYJEDLlCQ

[2]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'method' is not JSON serializable

**Comment by gi0baro** [comment]
@josejachuf just tested with the bloggy example and I can't reproduce your issue. Tested both with python 2.7 and 3.6

Did you changed the models or made anything else on the app?

**Comment by josejachuf** [comment]
I found the problem. It happens when I use signed urls, when I inject the sign function

app.injectors = [SignInjector()]

The error starts to occur

[signature.py.txt](https://github.com/gi0baro/weppy-REST/files/1052790/signature.py.txt)

**Comment by josejachuf** [comment]
I do not know how to solve it?

**Comment by josejachuf** [comment]
@gi0baro The same error occurs with any injector used:
for example:

```
class MyInjector(Injector):
    @staticmethod
    def upper(value):
        return value.upper()
```

Why try to serialize other things besides the Posts?

> {'data': [{'title': 'AAAAAAAA', 'text': 'aaaaaa'}, {'title': 'BBBBBB', 'text': '121212'}, {'title': 'CCC', 'text': 'ccc'}, {'title': 'DDDD', 'text': 'ddddd'}, {'title': 'ererere', 'text': 'erererer'}, {'title': 'lalalala', 'text': 'asasas'}], 'close': <bound method Pipe.close of <signature.SignTest object at 0x808147f28>>, 'on_pipe_failure': <bound method Pipe.on_pipe_failure of <signature.SignTest object at 0x808147f28>>, 'on_pipe_success': <bound method Pipe.on_pipe_success of <signature.SignTest object at 0x808147f28>>, 'open': <bound method Pipe.open of <signature.SignTest object at 0x808147f28>>, 'upper': <function SignTest.upper at 0x807dca378>}


[error.zip](https://github.com/gi0baro/weppy-REST/files/1053341/error.zip)

**Comment by gi0baro** [comment]
@josejachuf 'cause weppy is consistent above modules. You added an injector over your entire app, so weppy inject its content over every route in your application. The error is caused by the fact the contents of your injector are not JSON serializable. In order to fix that, you have to remove the injector from rest routes. So you'd better create a module for routes that need injection:

```python
crud = app.module(__name__, 'crud')
crud.injectors = [MyInjector()]

@crud.route('/')
def normal_route():
    # code

apis = app.module(__name__, 'apis')
posts = apis.rest_module(__name__, 'posts', Post, url_prefix='/posts')
```

**Comment by josejachuf** [comment]
Thanks @gi0baro,

I understand what it says about injecting only where it is needed. But out of curiosity, how do you remove the injector from rest routes?

**Comment by gi0baro** [comment]
@josejachuf as I posted in the example above:
- remove the injector from the application ones
- put the routes on which you need the injector on a separated module and add the injector only on the module
- everything else on the application and other modules doesn't have the injector

**Comment by josejachuf** [comment]
Is there any way to do the opposite: inject the entire application and then remove where I do not need it?

**Comment by gi0baro** [comment]
@josejachuf nope, the pipeline and the injector are shared between all the routes: having instances duplication would mean an higher and useless RAM usage :)

**Comment by josejachuf** [comment]
Ok. Thanks
