### ISSUE TITLE
Add support for "OPTIONS" HTTP method

### ISSUE THREAD

**Issue by guy881** [gi0baro/weppy-REST#4]
Hey, it would be great if extension could support "OPTIONS" method, which is send by default before  request modifying resource, when using CORS.

Preflighted requests are described here and are very common use case. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests

For me it was enough to change `_methods_map` inside `_after_initialize` function in class `RESTModule`.
I changed `'read': (self._path_rid, 'get'),` to `'read': (self._path_rid, ['get', 'options'])`

**Comment by gi0baro** [comment]
@guy881 you can implement it aside from the REST extension. Using standard weppy pipeline and routes, I usually do this:

```python
from weppy import request, response
from weppy.pipeline import Pipe

class CORS(Pipe):
    def open(self):
        response.headers["Access-Control-Allow-Origin"] = request.headers.get('Origin', '*')
        response.headers["Access-Control-Allow-Credentials"] = "true"
        response.headers["Access-Control-Allow-Methods"] = "OPTIONS, GET, POST, PUT, PATCH, DELETE"
        response.headers["Access-Control-Allow-Headers"] = \
            "Origin, Content-Type, Accept, Authorization"

app.pipeline = [CORS()]

@app.route('/<any:p>', methods='options')
def _options(p):
    return ""
```

**Comment by guy881** [comment]
Wow, that's cool! Thank you @gi0baro. :)

**Comment by gi0baro** [comment]
you're welcome :)
