### ISSUE TITLE
About serializer

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy-REST#6]
Hi @gi0baro 
I have a situation similar to [1] with the difference that TaskTag has its own serializer. This serializer has certain rules of what and how to show the attributes.

I want to include the last "TaskTag" in my Serializer Tag, but obviously all the rules I mentioned before are lost.
Something that I had already commented on another opportunity (google groups or weppy github, I do not remember) is that you can not access the rowattr of the model implicitly.

It would be great to be able to do something like this:

```
class CustomTaskSerializer(Serializer):
    def last_tag(self, row):
        return row.tags().last()
```
        
and have all the TaskTag fields as I wish (custom serialized or with the rowattr)

Jose
Best Regards

[1] https://github.com/gi0baro/weppy-REST#serializers

**Comment by josejachuf** [comment]
I solved it this way:

```
from weppy_rest import RESTModule, Serializer, serialize

from myapp import Task, Tag
from .tags import CustomTagSerializer

class CustomTaskSerializer(Serializer):
    #def last_tag(self, row):
    #    return row.tags().last()
    
    def tags(self, row):
        MyTagSerializer = CustomTagSerializer(Tag)
        return serialize(row.tags(), MyTagSerializer)
```

Jose

**Comment by gi0baro** [comment]
@josejachuf yep, that's the way it's intended to be done :)
